# See ../README.txt
include ../common/arduino.mk

CFLAGS += -I../common 
CFLAGS += -I../lib/arduino/cores/arduino
CFLAGS += -I../lib/WiShield

app.elf: build/deps/wishield.a build/deps/arduinocore.a

