# See ../README.txt
include ../common/arduino.mk

CFLAGS += -I../common 
CFLAGS += -I../lib/arduino/cores/arduino
CFLAGS += -I../lib/HughesyShiftBrite

app.elf: build/deps/hughesyshiftbrite.a build/deps/arduinocore.a
